import "./globals.css";
import type { Metadata } from "next";
import { Montserrat, Lato } from "next/font/google";

const monserrat = Montserrat({ subsets: ["latin"] });
const lato = Lato({ weight: ["400"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={monserrat.className + " " + lato.className}>
        {children}
      </body>
    </html>
  );
}
